// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo07OO3ypAlghYxo4-S6OEGEb34x_5MQ8',
    appId: '1:937254771313:web:eb559dde10c49f1f2a19d0',
    messagingSenderId: '937254771313',
    projectId: 'fir-flutter-tutorial-app',
    authDomain: 'fir-flutter-tutorial-app.firebaseapp.com',
    databaseURL: 'https://fir-flutter-tutorial-app-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-tutorial-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5nmng9fvhs5V1_Msu-1PHQaw7ZlmbOAY',
    appId: '1:937254771313:android:dcc77233bd7c462a2a19d0',
    messagingSenderId: '937254771313',
    projectId: 'fir-flutter-tutorial-app',
    databaseURL: 'https://fir-flutter-tutorial-app-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-tutorial-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzo6XLxyQQD1ijsdeOIHylCoZLJBI6h_Y',
    appId: '1:937254771313:ios:bd3964c03ac2304c2a19d0',
    messagingSenderId: '937254771313',
    projectId: 'fir-flutter-tutorial-app',
    databaseURL: 'https://fir-flutter-tutorial-app-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-tutorial-app.appspot.com',
    iosClientId: '937254771313-4237d2amgtu528psauip4badtmisgl99.apps.googleusercontent.com',
    iosBundleId: 'lk.dilshan.flutterNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzo6XLxyQQD1ijsdeOIHylCoZLJBI6h_Y',
    appId: '1:937254771313:ios:bd3964c03ac2304c2a19d0',
    messagingSenderId: '937254771313',
    projectId: 'fir-flutter-tutorial-app',
    databaseURL: 'https://fir-flutter-tutorial-app-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-tutorial-app.appspot.com',
    iosClientId: '937254771313-4237d2amgtu528psauip4badtmisgl99.apps.googleusercontent.com',
    iosBundleId: 'lk.dilshan.flutterNotes',
  );
}
